controller_list:
  #- name: "/ur5/manipulator_joint_trajectory_controller"
  #TODO name sim und realitaet unterschiedlich sim oben realitaet unten
  - name: ""
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint